### ISSUE TITLE
Crash when using Glad on Vulkan with NSight

### ISSUE THREAD

**Issue by akioCL** [Dav1dde/glad#298] opened 2020-09-15 07:21 UTC
When using glad for Vulkan with NSight enabled, there's a crash when calling gladLoaderLoadVulkan.

Callstack:
- glad_vk_has_extension(const char *) Line 12549 
- glad_vk_find_extensions_vulkan(VkPhysicalDevice_T * physical_device) Line 12566
- gladLoadVulkanUserPtr(VkPhysicalDevice_T * physical_device, void()(void *, const char *) load, void * userptr) Line 12873
- gladLoaderLoadVulkan(VkInstance_T *) Line 13518

`static int glad_vk_has_extension(const char *name, uint32_t extension_count, char **extensions) {
    uint32_t i;

    for (i = 0; i < extension_count; ++i) {
        if(strcmp(name, extensions[i]) == 0) {  ----------> Crash here accessing an invalid index
            return 1;
        }
    }

    return 0;
}`

The problem is in the "glad_vk_get_extensions function". For some weird reason, the first time calling glad_vkEnumerateDeviceExtensionProperties(physical_device, NULL, &device_extension_count, NULL); it returns device_extension_count = 116.

But the second is called (a couple of lines later) glad_vkEnumerateDeviceExtensionProperties(physical_device, NULL, &device_extension_count, ext_properties); it returns device_extension_count = 115.

This makes the variable "total_extension_count" have the wrong value. Causing a crash later when accessing index 115 in the extension arrays.

Apparently this is due to a bug in the loader: https://github.com/KhronosGroup/Vulkan-Loader/issues/348

**Comment by Dav1dde** [comment] 2020-09-15 20:53
Unfortunately I cannot reproduce this on my machine:
![image](https://user-images.githubusercontent.com/255721/93261897-a51b9680-f7a3-11ea-80be-6173168b53f7.png)

From what I can see, the call with `NULL` should return more than the call actually loading the extensions. What happens is, the array allocated for the extensions is too big (+1), allocation occurs with `calloc`, which then means the last element(s) of the array contain NULL.

This becomes easy to debug by just manually adding +1 to the first response (either modifying the code or in gdb):
![image](https://user-images.githubusercontent.com/255721/93262580-c03ad600-f7a4-11ea-8cc6-edbc660eff0b.png)

So the fix should just be to add a safety check for null elements in the `strcmp`. Everything else just passes the pointer to `free` which is perfectly fine to be called with `NULL`.

We don't need to change anything else because according to the linked ticket the extension count is always supposed to be equal and with this bug the NULL call always returns an equal amount or more -> the array can only be too big not too small.

@akioCL I pushed a fix, can you check if that works for you now?

**Closed** 2020-09-18 14:57 UTC
Labels: C, Vulkan, bug, glad2

**Comment by akioCL** [comment] 2020-09-19 12:22
Thanks for the quick turnaround. I just tested the fix and it worked as expected. Thanks!

**Comment by akioCL** [comment] 2020-09-19 12:23
> Unfortunately I cannot reproduce this on my machine:
> ![image](https://user-images.githubusercontent.com/255721/93261897-a51b9680-f7a3-11ea-80be-6173168b53f7.png)
> 
> From what I can see, the call with `NULL` should return more than the call actually loading the extensions. What happens is, the array allocated for the extensions is too big (+1), allocation occurs with `calloc`, which then means the last element(s) of the array contain NULL.
> 
> This becomes easy to debug by just manually adding +1 to the first response (either modifying the code or in gdb):
> ![image](https://user-images.githubusercontent.com/255721/93265129-6fc57780-f7a8-11ea-9c39-5a7cd55fb13a.png)
> ![image](https://user-images.githubusercontent.com/255721/93262580-c03ad600-f7a4-11ea-8cc6-edbc660eff0b.png)
> 
> So the fix should just be to add a safety check for null elements in the `strcmp`. Everything else just passes the pointer to `free` which is perfectly fine to be called with `NULL`.
> 
> We don't need to change anything else because according to the linked ticket the extension count is always supposed to be equal and with this bug the NULL call always returns an equal amount or more -> the array can only be too big not too small.
> 
> @akioCL I pushed a fix, can you check if that works for you now?

Thanks for the quick turnaround. I just tested the fix and it worked as expected. Thanks!
