### ISSUE TITLE
On-demand function loading?

### ISSUE THREAD

**Issue by JPGygax68** [Dav1dde/glad#215] opened 2019-06-04 11:47 UTC
Is there a way to have GLAD obtain function pointers on first access?

In our project, we're using the 4.6 + compatibility profile with all extensions just to be sure that everything is available, but initialization takes 6 seconds on my machine (recent NVidia GPU).

**Comment by Dav1dde** [comment] 2019-06-04 14:40
Not yet.

This is on my TODO but not the highest priority because for the most part generating a loader with compatibility and all extensions is most likely not necessary.

Out of curiosity, why are you including all extensions and not just the ones you need?

If you need a loader with on demand function loading right now, maybe [libepoxy](https://github.com/anholt/libepoxy) is an option.

**Comment by JPGygax68** [comment] 2019-06-04 14:59
Thank you @Dav1dde. You might call it a form of lazyness: we have a main program written in Fortran that uses only very basic OpenGL (I think there's nothing there beyond 1.1), but quite a few DLLs that use more advanced features (such as shaders). All modules however share the same OpenGL context(s), so filtering out stuff that is not needed would work great today, but break mysteriously in a week, month or year.

If you have a Patreon account or something similar, I think the CEO would not mind contributing something towards that feature.

**Comment by Dav1dde** [comment] 2019-06-04 15:26
Are you using the internal loader (`gladLoadGL()`) or the function loader of e.g. glfw (`glfwGetProcAddress`), SDL (`SDL_GL_GetProcAddress`)?

Let's see maybe I can hack something together tonight, this would be a feature of the glad2 branch so you might have to migrate to glad2.

If you want to contribute money (in no means necessary) we probably should discuss this via email (possibly in German).

**Comment by Dav1dde** [comment] 2019-06-04 19:56
I just implemented this on the glad2 branch, the implementation has a few drawbacks to the initialize once approach.

* `GLAD_` constants are removed
* No version feedback (return value of loader)
* There are no safeguards for segmentation faults, if the loader returns NULL for a function you're trying to call, it will segfault.

I went ahead and implemented it for all APIs (EGL, GL, GLES1, GLES2, GLX, Vulkan and WGL), it also integrates with the built-in loader, I'd recommend to use the loader function of your windowing library though.

Any feedback welcome. I'll leave this issue open for now, in case you have questions/feedback.

**Comment by JPGygax68** [comment] 2019-06-04 20:25
@Dav1dde Wow! You did all the work in the time it took me to go through an extended dinner + digestion. Very much appreciated!

Just to clarify, we're not using a windowing system, we call directly into the Windows API to create our windows and create and attach OpenGL contexts to them. Therefore, at least up until now, I used gladLoadGL() to init the function pointers, which I believe calls `wglGetProcAddress()` (though indirectly through an internal function pointer). Does that mean I should now use `wglGetProcAddress()` explicitly?

**Comment by Dav1dde** [comment] 2019-06-04 20:41
The internal loader is unnecessary if you're using glfw, SDL, Qt, etc - since you're creating the context yourself, it makes sense to use the glad builtin loader.

Sounds like it was a good dinner! I didn't really taste mine .. too focused on failing tests :p

PS: If you're using the glad2 website, make sure to check the loader option, it's not enabled by default anymore.

**Comment by JPGygax68** [comment] 2019-06-04 21:31
It was a very good dinner, got invited to eat the products of a cooking course graduation exam. :-)

I tried the generator just now, and chose the header-only variant. But now the linker complains about `unresolved external symbol glad_debug_glBindFramebuffer`, so I guess that variant is not suited for my purposes. I will make a new attempt tomorrow.

**Comment by Dav1dde** [comment] 2019-06-04 21:34
Try without a debug build, that's one of the things I haven't gotten around to testing yet. Maybe a few resources that may help you:

* [gl_glfw_on_demand example](https://github.com/Dav1dde/glad/blob/glad2/example/c/gl_glfw_on_demand.c)
* [on demand gl tests](https://github.com/Dav1dde/glad/tree/glad2/test/c/run/gl/on-demand)

I'll look into the interaction with a debug build tomorrow after work (mh I thought it would work out of the box...)

**Comment by Dav1dde** [comment] 2019-06-05 19:42
I can't reproduce your problem, maybe you were using a glad1-debug build but did not select debug in glad2 or forgot to recompile a few static libraries?

I just pushed some major fixes for debug contexts in 5391cecd33d442a6c8d57652082f88003d6f341d, they should work properly now.

**Comment by JPGygax68** [comment] 2019-06-05 20:30
I should mention that I've been using the web service to generate the code. I'll try to get the python script working.

**Comment by Dav1dde** [comment] 2019-06-05 20:34
I updated the webservice after every commit, so that should be fine.

**Comment by JPGygax68** [comment] 2019-06-05 21:45
![grafik](https://user-images.githubusercontent.com/795272/58992747-f0e34000-87eb-11e9-856b-f8f64753851d.png)

I just created Glad using the above parameters, and `gladLoadGL()` in `gl.h`, but does not have an implementation.

**Comment by Dav1dde** [comment] 2019-06-06 05:28
`gladLoadGL` shouldn't be in the header anymore, I'll have to remove it. If you generate with the loader you don't have to call any glad functions anymore it initializes itself on the first gl call.

PS: function pointer aliasing was implemented as a post loading step, this doesn't work anymore. For now it doesn't do anything, this will get fixed though.

**Comment by JPGygax68** [comment] 2019-06-06 12:41
Thank you! I managed to get my app to launch, but now it aborts with a null pointer when trying to use the first `wgl` function:

`bStatus = wglChoosePixelFormatARB(hDC, iAttributes, fAttributes,1, pixelFormats, &numFormats);`

Does that mean that `wgl` functions must still be loaded explicitly?

P.S. I'm not sure what "function pointer aliasing" was supposed to be, I only checked it as a kind of stress test - to see if it would still work with the maximum number of options enabled.

**Comment by Dav1dde** [comment] 2019-06-06 12:54
Ah, thanks for testing ... will be fixed.

For now you'll have to generate twice, OpenGL with on-demand enabled, WGL without.

> P.S. I'm not sure what "function pointer aliasing" was supposed to be, I only checked it as a kind of stress test - to see if it would still work with the maximum number of options enabled.

Some functions existed as an extension `glFooARB` they were later introduced into core `glFoo` function pointer aliasing makes sure if you're on an older maching with only the extension `glFoo` will resolve to `glFooARB` instead of failing with a segfault.

**Comment by JPGygax68** [comment] 2019-06-06 14:24
Thanks! I generated wgl like this:
![grafik](https://user-images.githubusercontent.com/795272/59040631-5c262400-8877-11e9-96b5-209b142f5cb0.png)
but unfortunately `gladLoadWG()` does not have an implementation, only a declaration.

**Comment by Dav1dde** [comment] 2019-06-06 15:01
You need to generate WGL *without* on demand for now.

**Comment by JPGygax68** [comment] 2019-06-06 15:18
My bad, sorry. Works now!

**Comment by JPGygax68** [comment] 2019-06-06 15:33
I can see that the debug feature could be very helpful to us (so far, we've been using wrapper macros). But do you think that feature could be controlled by a compile-time definition instead of at code generation time?

Let me know if this should be a separate feature request. Btw, I wrote to your github email address, did you get my message?

**Comment by Dav1dde** [comment] 2019-06-06 15:50
There is a feature request about swapping the debug implementations in and out at runtime, would this satisfy your needs? And yeah we should discuss this in a separate issue.

I did get your email and replied to it, I might have answered from a different email (admin instead of github).

**Comment by JPGygax68** [comment] 2019-06-06 18:04
Hm... Switching debug on/off at runtime would definitely be useful, but I'd say build-time would be sufficient.

**Comment by Dav1dde** [comment] 2019-07-06 16:51
WGL should have been fixed with f55b4f9f8cdfddf0f2a9690799b408df3719699c

And I just closed #68 - now you can enable/disable the debug functionality at runtime.

**Closed** 2019-07-06 16:51 UTC
Labels: C, enhancement, glad2, question
