### ISSUE TITLE
Unaliased GL_EXT_framebuffer_object functions 

### ISSUE THREAD

**Issue by ccawley2011** [Dav1dde/glad#366] opened 2022-05-23 16:02 UTC
When aliasing is enabled, most of the functions from `GL_EXT_framebuffer_object` are aliased to the equivalent functions from OpenGL 3.0/OpenGL ES 2.0/`GL_ARB_framebuffer_object`, however the `glBindFramebufferEXT` and `glBindRenderbufferEXT` don't get aliased, resulting in a crash when `glBindFramebuffer` or `glBindRenderbuffer` are called on systems that only have `GL_EXT_framebuffer_object`.

**Comment by Dav1dde** [comment] 2022-05-24 08:10
It looks like the alias information is missing in the spec, compare `glGenRenderbuffersEXT` with an `<alias>` element:
```xml
        <command>
            <proto>void <name>glGenRenderbuffersEXT</name></proto>
            <param><ptype>GLsizei</ptype> <name>n</name></param>
            <param class="renderbuffer" len="n"><ptype>GLuint</ptype> *<name>renderbuffers</name></param>
            <alias name="glGenRenderbuffers"/>
            <glx type="vendor" opcode="1423"/>
        </command>
```

And here the two functions you mentioned without `<alias>`:
```
        <command>
            <proto>void <name>glBindFramebufferEXT</name></proto>
            <param group="FramebufferTarget"><ptype>GLenum</ptype> <name>target</name></param>
            <param class="framebuffer"><ptype>GLuint</ptype> <name>framebuffer</name></param>
            <glx type="render" opcode="4319"/>
        </command>

        <command>
            <proto>void <name>glBindRenderbufferEXT</name></proto>
            <param group="RenderbufferTarget"><ptype>GLenum</ptype> <name>target</name></param>
            <param class="renderbuffer"><ptype>GLuint</ptype> <name>renderbuffer</name></param>
            <glx type="render" opcode="4316"/>
        </command>
```

Do you want to open an issue/mr on the [official repo](https://github.com/KhronosGroup/OpenGL-Registry) yourself or do you want me to do that?

**Comment by lephilousophe** [comment] 2022-05-26 15:11
This issue comes from a PR in scummvm/scummvm#3907.

From [ARB framebuffer object extension](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_framebuffer_object.txt):
> Note that the functions BindFramebuffer and
   BindFramebufferEXT are not aliases and neither are the functions
   BindRenderbuffer and BindRenderbufferEXT.  Because object creation
   occurs when the framebuffer object is bound for the first time, a
   framebuffer object can be shared across contexts only if it was first
   bound with BindFramebufferEXT.  Framebuffers first bound with
   BindFramebuffer may not be shared across contexts.  Framebuffer
   objects created with BindFramebufferEXT may subsequently be bound
   using BindFramebuffer.  Framebuffer objects created with
   BindFramebuffer may be bound with BindFramebufferEXT provided they are
   bound to the same context they were created on.

So this doesn't seem to be a bug in GLAD or the XML specs.
The XML specs even have a different opcode for both functions (4319 vs. 236).

**Comment by Dav1dde** [comment] 2022-05-26 16:17
Thanks for updating this, so this is intended behaviour and we can close the issue?

**Comment by lephilousophe** [comment] 2022-05-26 19:11
I suppose yes.

**Closed** 2022-05-27 09:56 UTC
Labels: GL, specification-bug
